# Generated by Django 2.0.4 on 2018-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Remote Server',
            },
        ),
    ]
